### ISSUE TITLE
can't create a model

### ISSUE THREAD

**Issue by mstww** [giniedp/nw-models#1]
What am I missing?
![image](https://github.com/giniedp/nw-models/assets/57295889/cdf1500b-460b-40e0-87f2-32a5e52acb0a)

**Comment by giniedp** [comment]
what command did you run

**Comment by giniedp** [comment]
what does your `.env` file look like?
you did run `yarn convert-tables` and `yarn convert-slices`, right?
can you tell this directory size and file count of the unpacked directory? Also intermediate directories as well (tables, slices, transit).
I'm converting right now for current release and so far no issues

**Comment by giniedp** [comment]
@mstww sorry for not having a follow up on this issue. In the mean time the project has been rewritten and does not rely on 3rd party tools to convert the geometry files any more. i'll close this issue for now. Feel free to open a new one if you encounter issues with the new workflow.
