### ISSUE TITLE
converting slices - not completing or progressing

### ISSUE THREAD

**Issue by Chris971991** [giniedp/nw-models#2]
using the convert-slices command prompt only converts a small portion of the slices and the progress runs indefinitely. I left it to convert for 6.5 hours, and it eventually froze in the cmd.

It makes the ones below and stops:
![image](https://github.com/giniedp/nw-models/assets/26810613/3c41261d-4a46-4bd7-b314-99aee0ad9c7f)

Stays at this progress:
![image](https://github.com/giniedp/nw-models/assets/26810613/c6a29bcb-1c34-4a06-9f67-2459cb526cd1)

**Comment by giniedp** [comment]
What was the exact command you run? From the image i can't see at what stage it gets blocked.

The slices command is a tool to explore specific or individual slices. Please do not run that command on all game files. There are way too many slices and processing all of them will take ages. Especially if you use the recursive option.

**Comment by Chris971991** [comment]
That was running the convert-slices. I understand about not running them at all now.

Trying it sinuglar, I believe I am doing it wrong:

![image](https://github.com/giniedp/nw-models/assets/26810613/d8828801-7d66-48c0-932f-97fa68639685)

Any change you could give me an example command?

**Comment by giniedp** [comment]
the `-slice` will only work on `.dynamicslice` files. You are running it on a `.meta` file which has a different data structure.

This is what you want
```
pnpm convert-models -slice slices/dungeon/objects/heartgenesis/heartgenesis_env_base.dynamicslice.json
```

**Comment by giniedp** [comment]
or to process multiple files you can use a glob pattern
```
pnpm convert-models -slice slices/dungeon/objects/heartgenesis/**/*.dynamicslice.json
```
Just make sure that the glob does not match too many files.
Processing slices this way may loose some hierarchy transormations. But it is a godd way to get an understanding what geometry it defines or what part of a dungeon it is for.

Feel free to ask questions on the discord: https://discord.gg/PWxUwUagVX

**Comment by giniedp** [comment]
Sorry, i was on the wrong track with this question. You're right, the convert-slices process did not finish. Seems like the spawned tool needs the stdout buffer to be constantly flushed, which i ignored to reduce the log output.
Should be fxed now.
